import { execFileSync } from 'node:child_process'
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import * as git from './gitops'

let root: string
let cwd: string
const command = (dir: string, ...args: string[]): string => execFileSync('git', ['-C', dir, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim()
async function init(dir: string): Promise<void> {
  await mkdir(dir, { recursive: true })
  command(dir, 'init', '-q', '-b', 'main')
  command(dir, 'config', 'user.name', 'M3b Test')
  command(dir, 'config', 'user.email', 'm3b@example.test')
  command(dir, 'config', 'commit.gpgSign', 'false')
}
async function write(name: string, content: string): Promise<void> { await writeFile(join(cwd, name), content) }
async function commit(message: string): Promise<void> { await git.gitStageAll(cwd); await git.gitCommitStaged(cwd, message) }
async function remote(): Promise<string> {
  const bare = join(root, 'remote.git')
  await mkdir(bare)
  command(bare, 'init', '--bare', '-q', '-b', 'main')
  command(cwd, 'remote', 'add', 'upstream', bare)
  return bare
}
beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), 'tc-m3b-git-'))
  cwd = join(root, 'repo')
  await init(cwd)
  await write('file.txt', 'first\n' + 'middle\n'.repeat(20) + 'last\n')
  await commit('initial')
})
afterEach(async () => { vi.unstubAllEnvs(); await rm(root, { recursive: true, force: true }) })

describe('donor git methods', () => {
  it('diffStats counts HEAD changes, untracked lines and unborn HEAD', async () => {
    expect(await git.gitDiffStats(cwd)).toEqual({ files: 0, additions: 0, deletions: 0 })
    await write('file.txt', 'changed\n')
    await write('new.txt', 'one\ntwo')
    expect(await git.gitDiffStats(cwd)).toEqual({ files: 2, additions: 3, deletions: 22 })
    const unborn = join(root, 'unborn')
    await init(unborn)
    await writeFile(join(unborn, 'staged.txt'), 'one\ntwo\n')
    await git.gitStageFile(unborn, 'staged.txt')
    await writeFile(join(unborn, 'new.txt'), 'three\n')
    expect(await git.gitDiffStats(unborn)).toEqual({ files: 2, additions: 3, deletions: 0 })
    expect((await git.gitBranches(unborn)).branches).toEqual([{ name: 'main', current: true, remote: null }])
    expect(await git.gitLog(unborn)).toEqual([])
    expect(await git.gitDiffStats(root)).toEqual({ files: 0, additions: 0, deletions: 0 })
  })

  it('stageContents stages one of two hunks and commitStaged preserves the unstaged hunk and mode', async () => {
    await chmod(join(cwd, 'file.txt'), 0o755)
    await commit('executable')
    const original = await readFile(join(cwd, 'file.txt'), 'utf8')
    const staged = original.replace('first', 'FIRST')
    const current = staged.replace('last', 'LAST')
    await write('file.txt', current)
    await git.gitStageContents(cwd, 'file.txt', staged)
    expect(command(cwd, 'show', ':file.txt')).toBe(staged.trimEnd())
    expect(command(cwd, 'ls-files', '--stage')).toMatch(/^100755 /)
    expect(command(cwd, 'diff', '--cached')).toContain('+FIRST')
    expect(command(cwd, 'diff', '--cached')).not.toContain('+LAST')
    expect(command(cwd, 'diff')).toContain('+LAST')
    expect(command(cwd, 'diff')).not.toContain('+FIRST')
    expect((await git.gitDiffIndex(cwd)).files[0]).toMatchObject({ staged: true, unstaged: true, additions: 2, deletions: 2 })
    expect((await git.gitStagedContext(cwd)).patch).not.toContain('+LAST')
    await git.gitCommitStaged(cwd, '  one hunk\n\n# stripped comment  ')
    expect(command(cwd, 'show', 'HEAD:file.txt')).toBe(staged.trimEnd())
    expect(await readFile(join(cwd, 'file.txt'), 'utf8')).toBe(current)
    expect(command(cwd, 'diff', '--cached')).toBe('')
    expect(command(cwd, 'diff')).toContain('+LAST')
  })

  it('fileDiff defaults to index, supports HEAD, subdirectories, binary, deletion and the size cap', async () => {
    await write('file.txt', 'index\n')
    await git.gitStageFile(cwd, 'file.txt')
    await write('file.txt', 'disk\n')
    expect(await git.gitFileDiff(cwd, 'file.txt')).toMatchObject({ original: 'index\n', current: 'disk\n', binary: false, tooLarge: false })
    expect((await git.gitFileDiff(cwd, 'file.txt', 'HEAD')).original).toContain('first\n')
    await mkdir(join(cwd, 'nested'))
    await write('nested/a.txt', 'index nested\n')
    await git.gitStageFile(cwd, 'nested/a.txt')
    await git.gitStageContents(join(cwd, 'nested'), 'a.txt', 'partial nested\n')
    expect((await git.gitFileDiff(join(cwd, 'nested'), 'a.txt')).original).toBe('partial nested\n')
    await write('nul.bin', 'a\0b')
    expect(await git.gitFileDiff(cwd, 'nul.bin')).toMatchObject({ binary: true, original: '', current: '', status: 'untracked' })
    await write('big.txt', 'x'.repeat(8 * 1024 * 1024 + 1))
    expect(await git.gitFileDiff(cwd, 'big.txt')).toMatchObject({ tooLarge: true, current: '' })
    await git.gitStageFile(cwd, 'big.txt')
    await write('big.txt', 'small')
    expect(await git.gitFileDiff(cwd, 'big.txt')).toMatchObject({ tooLarge: true, original: '', current: '' })
    await rm(join(cwd, 'file.txt'))
    expect(await git.gitFileDiff(cwd, 'file.txt')).toMatchObject({ status: 'deleted', current: '' })
    await expect(git.gitFileDiff(root, 'file.txt')).rejects.toThrow('Not a git repository')
  })

  it('stageFile/unstageFile/stageAll/unstageAll preserve working contents and handle literal names', async () => {
    await write('file.txt', 'changed\n')
    await write('[a].txt', 'literal\n')
    await write('a.txt', 'other\n')
    await git.gitStageFile(cwd, '[a].txt')
    expect(command(cwd, 'diff', '--cached', '--name-only')).toBe('[a].txt')
    await git.gitUnstageFile(cwd, '[a].txt')
    expect(command(cwd, 'diff', '--cached')).toBe('')
    await git.gitStageAll(cwd)
    expect((await git.gitDiffIndex(cwd)).files.every((f) => f.staged)).toBe(true)
    await git.gitUnstageAll(cwd)
    expect(command(cwd, 'diff', '--cached')).toBe('')
    expect(await readFile(join(cwd, '[a].txt'), 'utf8')).toBe('literal\n')
  })

  it('diffIndex retains files whose staged and unstaged changes cancel and handles unusual names', async () => {
    const original = await readFile(join(cwd, 'file.txt'), 'utf8')
    await git.gitStageContents(cwd, 'file.txt', 'staged\n')
    await write('file.txt', original)
    await write('spaces\tand\nlines.txt', 'one\n')
    const index = await git.gitDiffIndex(cwd)
    expect(index.files.find((f) => f.relative === 'file.txt')).toMatchObject({ additions: 0, deletions: 0, staged: true, unstaged: true })
    expect(index.files.find((f) => f.relative === 'spaces\tand\nlines.txt')).toMatchObject({ additions: 1, status: 'untracked' })
    expect(index).toMatchObject({ branch: 'main', remote: null, upstream: null, defaultBranch: 'main', ahead: 0, behind: 0, aheadOfDefault: 0 })
  })

  it('discardFile restores index contents and deletes untracked files and directories', async () => {
    await git.gitStageContents(cwd, 'file.txt', 'keep staged\n')
    await write('file.txt', 'discard\n')
    await git.gitDiscardFile(cwd, 'file.txt')
    expect(await readFile(join(cwd, 'file.txt'), 'utf8')).toBe('keep staged\n')
    expect(command(cwd, 'diff', '--cached')).toContain('+keep staged')
    await write('new.txt', 'remove\n')
    await git.gitDiscardFile(cwd, 'new.txt')
    await expect(readFile(join(cwd, 'new.txt'))).rejects.toMatchObject({ code: 'ENOENT' })
    await mkdir(join(cwd, 'untracked'))
    await write('untracked/child.txt', 'remove\n')
    await git.gitDiscardFile(cwd, 'untracked')
    await expect(readFile(join(cwd, 'untracked/child.txt'))).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('stagedContext falls back to HEAD and untracked names and errors when clean', async () => {
    await expect(git.gitStagedContext(cwd)).rejects.toThrow('No changes to summarize')
    await write('file.txt', 'unstaged\n')
    await write('new.txt', 'new\n')
    const result = await git.gitStagedContext(cwd)
    expect(result).toMatchObject({ branch: 'main' })
    expect(result.summary).toContain('Untracked files:\nnew.txt')
    expect(result.patch).toContain('+unstaged')
    await expect(git.gitCommitStaged(cwd, '  ')).rejects.toThrow('Commit message cannot be empty')
    await expect(git.gitCommitStaged(cwd, 'no index changes')).rejects.toThrow()
  })

  it('branches/createBranch/checkout/stash preserve donor branch and dirty-tree behavior', async () => {
    expect(await git.gitCreateBranch(cwd, ' feature ')).toBe('feature')
    await write('file.txt', 'feature\n')
    await commit('feature change')
    expect(await git.gitCheckout(cwd, 'main')).toBe('main')
    await write('file.txt', 'dirty\n')
    await write('untracked.txt', 'stash me\n')
    await expect(git.gitCheckout(cwd, 'feature')).rejects.toThrow('Your local changes would be overwritten. Commit or stash them first.')
    await git.gitStash(cwd, '  saved by M3b  ')
    expect(command(cwd, 'stash', 'list')).toContain('saved by M3b')
    expect(command(cwd, 'status', '--porcelain')).toBe('')
    expect(await git.gitCheckout(cwd, 'feature')).toBe('feature')
    expect((await git.gitBranches(cwd)).branches[0]).toEqual({ name: 'feature', current: true, remote: null })
    await expect(git.gitCreateBranch(cwd, 'feature')).rejects.toThrow('Branch feature already exists')
    await expect(git.gitCreateBranch(cwd, 'bad name')).rejects.toThrow("'bad name' is not a valid branch name")
    await expect(git.gitCheckout(cwd, 'absent')).rejects.toThrow('Branch absent not found')
    command(cwd, 'checkout', '--detach')
    expect(await git.gitBranches(cwd)).toMatchObject({ detached: true, current: command(cwd, 'rev-parse', '--short', 'HEAD') })
    expect(await git.gitBranches(root)).toEqual({ current: null, detached: false, branches: [] })
  })

  it('push, pull, sync and remote checkout work against a bare remote and second clone', async () => {
    const bare = await remote()
    await git.gitPush(cwd)
    expect(command(cwd, 'rev-parse', '--abbrev-ref', '@{upstream}')).toBe('upstream/main')
    const second = join(root, 'second')
    command(root, 'clone', '-q', bare, second)
    command(second, 'config', 'user.name', 'M3b Test')
    command(second, 'config', 'user.email', 'm3b@example.test')
    command(second, 'config', 'commit.gpgSign', 'false')
    await writeFile(join(second, 'second.txt'), 'incoming\n')
    await git.gitStageAll(second)
    await git.gitCommitStaged(second, 'incoming')
    await git.gitPush(second)
    await git.gitPull(cwd)
    expect(await readFile(join(cwd, 'second.txt'), 'utf8')).toBe('incoming\n')
    await write('local.txt', 'outgoing\n')
    await commit('outgoing')
    expect((await git.gitDiffIndex(cwd)).ahead).toBe(1)
    await git.gitSync(cwd)
    expect(command(bare, 'rev-parse', 'main')).toBe(command(cwd, 'rev-parse', 'HEAD'))
    await git.gitCreateBranch(cwd, 'remote-feature')
    await write('feature.txt', 'feature\n')
    await commit('remote feature')
    await git.gitSync(cwd)
    command(second, 'fetch', '-q')
    expect((await git.gitBranches(second)).branches).toContainEqual({ name: 'remote-feature', current: false, remote: 'origin' })
    expect(await git.gitCheckout(second, 'remote-feature', 'origin')).toBe('remote-feature')
    expect(command(second, 'rev-parse', '--abbrev-ref', '@{upstream}')).toBe('origin/remote-feature')
    const context = await git.gitRangeContext(cwd)
    expect(context).toMatchObject({ base: 'main', head: 'remote-feature' })
    expect(context.commitSummary).toContain('remote feature')
    expect(context.diffPatch).toContain('+feature')
  }, 30_000)

  it('sync merges divergent upstream history while pull refuses divergence', async () => {
    const bare = await remote()
    await git.gitPush(cwd)
    const second = join(root, 'second')
    command(root, 'clone', '-q', bare, second)
    command(second, 'config', 'user.name', 'M3b Test')
    command(second, 'config', 'user.email', 'm3b@example.test')
    command(second, 'config', 'commit.gpgSign', 'false')
    await writeFile(join(second, 'incoming.txt'), 'incoming\n')
    await git.gitStageAll(second)
    await git.gitCommitStaged(second, 'incoming')
    await git.gitPush(second)
    await write('outgoing.txt', 'outgoing\n')
    await commit('outgoing')
    await expect(git.gitPull(cwd)).rejects.toThrow()
    command(cwd, 'config', 'pull.rebase', 'false')
    await git.gitSync(cwd)
    expect(command(cwd, 'rev-list', '--parents', '-n', '1', 'HEAD').split(' ')).toHaveLength(3)
    expect(command(bare, 'rev-parse', 'main')).toBe(command(cwd, 'rev-parse', 'HEAD'))
  }, 30_000)

  it('rangeContext resolves a local default branch and log returns complete DTOs', async () => {
    await expect(git.gitRangeContext(cwd)).rejects.toThrow('No commits to include in a pull request')
    await git.gitCreateBranch(cwd, 'feature')
    await write('file.txt', 'feature\n')
    await commit('feature commit')
    expect(await git.gitRangeContext(cwd)).toMatchObject({ base: 'main', head: 'feature', commitSummary: 'feature commit\n' })
    const entries = await git.gitLog(cwd, 1)
    expect(entries).toHaveLength(1)
    expect(entries[0]).toEqual({ hash: command(cwd, 'rev-parse', 'HEAD'), short: command(cwd, 'rev-parse', '--short', 'HEAD'), subject: 'feature commit', author: 'M3b Test', date: expect.stringMatching(/^\d{4}-\d{2}-\d{2}T/) })
    await expect(git.gitPush(cwd)).rejects.toThrow('No git remote to push to')
  })

  it('clone validates URL and child name, clones a real repository and refuses collisions', async () => {
    const parent = join(root, 'clones')
    await mkdir(parent)
    vi.stubEnv('GIT_CONFIG_COUNT', '1')
    vi.stubEnv('GIT_CONFIG_KEY_0', `url.file://${cwd}.insteadOf`)
    vi.stubEnv('GIT_CONFIG_VALUE_0', 'https://m3b.invalid/source.git')
    const cloned = await git.gitClone('https://m3b.invalid/source.git', parent)
    expect(cloned).toBe(join(parent, 'source'))
    expect(command(cloned, 'rev-parse', 'HEAD')).toBe(command(cwd, 'rev-parse', 'HEAD'))
    await expect(git.gitClone('https://m3b.invalid/source.git', parent)).rejects.toThrow('already exists')
    await expect(git.gitClone('--upload-pack=evil', parent)).rejects.toThrow('Enter an https, ssh, or git URL')
    await expect(git.gitClone('https://m3b.invalid/..', parent)).rejects.toThrow('Could not infer repository name')
  })

  it('refuses relative path escapes and oversized stageContents', async () => {
    for (const relative of ['../outside', '/absolute', 'nested/../outside', 'a//b']) {
      for (const fn of [git.gitFileDiff, git.gitStageFile, git.gitUnstageFile, git.gitDiscardFile]) await expect(fn(cwd, relative)).rejects.toThrow('Invalid path')
      await expect(git.gitStageContents(cwd, relative, 'text')).rejects.toThrow('Invalid path')
    }
    await expect(git.gitStageContents(cwd, 'file.txt', 'é'.repeat(4 * 1024 * 1024 + 1))).rejects.toThrow('File too large')
  })
})
